import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'
import Nav from '../../components/Nav'

const Contact = () =>{
  return (
    <div>
      <Head>
        <title>Blog Website | Learn New Technologys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Nav />
      <main >
          <h2> Welcome Contact </h2>
      </main>

    
    </div>
  )
}

export default Contact